%import common.WS

statement: order ("\n" order) *

order: move_order
    | hold_order
    | support_order
    | convoy_move_order


move_order: unit WS MOVE WS province

hold_order: unit WS HOLD

support_order: unit WS SUPPORT WS move_order

convoy_move_order: unit WS CONVOY_MOVE WS province

HOLD : "h"
    | "hold"
    | "holds"

MOVE : "-"
     | "->"
     | "to"
     | "m"
     | "move"
     | "moves"

CONVOY_MOVE : "c-"
        | "cm"
        | "convoy -"
        | "convoy ->"
        | "convoy to"
        | "convoy m"
        | "convoy move"
        | "convoy moves"

SUPPORT : "s"
        | "support"
        | "supports"

CONVOY : "c"
        | "convoy"
        | "convoys"

CORE : "core"
    | "cores"

unit : (DISCRIPTOR WS)? province


DISCRIPTOR : /[afAF](?=\s)/

province : PROVINCE (WS PROVINCE) *

PROVINCE : /(?![fFaA]\s)[a-zA-Z\._]+/
